CREATE DATABASE ANAJ 
USER SYS IDENTIFIED BY manager 
USER SYSTEM IDENTIFIED BY manager 
LOGFILE 
GROUP 1 ('C:\app\User\oradata\ANAJ\redo\redo1.log') size 10M, 
GROUP 2 ('C:\app\User\oradata\ANAJ\redo\redo2.log') size 10M, 
GROUP 3 ('C:\app\User\oradata\ANAJ\redo\redo3.log') size 10M 
MAXLOGFILES 16 
MAXLOGMEMBERS 3 
MAXLOGHISTORY 1 
MAXDATAFILES 25 
MAXINSTANCES 1 
CHARACTER SET AL32UTF8 
DATAFILE 'C:\app\User\oradata\ANAJ\datafiles\system01.dbf' 
SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED 
EXTENT MANAGEMENT LOCAL 
SYSAUX DATAFILE 'C:\app\User\oradata\ANAJ\datafiles\sysaux01.dbf' 
SIZE 10M AUTOEXTEND ON 
NEXT 10M MAXSIZE UNLIMITED 
DEFAULT TEMPORARY TABLESPACE temp 
TEMPFILE 'C:\app\User\oradata\ANAJ\datafiles\temp01.dbf' 
SIZE 10M AUTOEXTEND ON MAXSIZE UNLIMITED 
UNDO TABLESPACE UNDOTBS1 
DATAFILE 'C:\app\User\oradata\ANAJ\datafiles\undotbs01.dbf' 
SIZE 10M AUTOEXTEND ON MAXSIZE UNLIMITED; 